INSERT ALL
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('01', 'KU3.03.04', 'IF-43-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('02', 'KU1.05.98', 'IF-43-11', 'CII2C9', 'Pengantar Informatika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('03', 'KU1.03.80', 'IF-41-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('04', 'KU3.04.14', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('05', 'KU3.04.16', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('06', 'KU1.04.98', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('07', 'KU1.05.59', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('08', 'KU3.04.64', 'IF-43-12', 'CII3E2', 'Logika Matematika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('09', 'KU3.04.20', 'IF-43-10', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('10', 'KU1.05.73', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('11', 'KU3.02.07', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('12', 'KU3.02.54', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('13', 'KU3.05.50', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('14', 'KU3.05.26', 'IF-44-05', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('15', 'KU3.04.90', 'IF-44-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('16', 'KU3.04.78', 'IF-44-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('17', 'KU2.03.62', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('18', 'KU1.05.77', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('19', 'KU1.03.86', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('20', 'KU2.04.88', 'IF-44-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('21', 'KU1.03.60', 'IF-42-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('22', 'KU1.03.09', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('23', 'KU2.05.16', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('24', 'KU3.05.51', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('25', 'KU3.05.90', 'IF-44-02', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('26', 'KU2.05.67', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('27', 'KU3.05.89', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('28', 'KU2.05.60', 'IF-42-09', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('29', 'KU3.05.32', 'IF-44-12', 'CII2C9', 'Pengantar Informatika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('30', 'KU3.05.23', 'IF-42-09', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('31', 'KU1.05.76', 'IF-42-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('32', 'KU2.05.82', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('33', 'KU3.05.07', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('34', 'KU3.04.82', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('35', 'KU2.05.51', 'IF-43-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('36', 'KU3.05.82', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('37', 'KU3.05.50', 'IF-43-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('38', 'KU3.04.94', 'IF-43-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('39', 'KU3.05.47', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('40', 'KU1.05.51', 'IF-43-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('41', 'KU3.05.63', 'IF-43-11', 'CII2C9', 'Pengantar Informatika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('42', 'KU3.05.52', 'IF-43-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('43', 'KU2.05.28', 'IF-42-11', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('44', 'KU2.02.95', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('45', 'KU3.05.08', 'IF-43-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('46', 'KU3.01.12', 'IF-43-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('47', 'KU3.04.80', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('48', 'KU3.05.56', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('49', 'KU3.05.97', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('50', 'KU3.04.93', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('51', 'KU2.05.50', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('52', 'KU1.04.64', 'IF-42-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('53', 'KU2.04.56', 'IF-43-10', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('54', 'KU3.05.46', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('55', 'KU3.05.48', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('56', 'KU2.01.76', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('57', 'KU3.05.32', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('58', 'KU2.04.80', 'IF-44-10', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('59', 'KU1.05.59', 'IF-41-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('60', 'KU1.04.75', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('61', 'KU3.04.98', 'IF-42-11', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('62', 'KU3.05.89', 'IF-41-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('63', 'KU2.05.43', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('64', 'KU2.05.43', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('65', 'KU1.05.34', 'IF-44-11', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('66', 'KU2.04.56', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('67', 'KU3.05.34', 'IF-42-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('68', 'KU3.04.41', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('69', 'KU2.05.68', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('70', 'KU3.05.42', 'IF-43-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('71', 'KU3.05.36', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('72', 'KU2.05.94', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('73', 'KU1.05.12', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('74', 'KU3.05.97', 'IF-41-10', 'CII3E2', 'Logika Matematika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('75', 'KU3.05.85', 'IF-41-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('76', 'KU2.04.64', 'IF-41-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('77', 'KU3.05.88', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('78', 'KU3.05.71', 'IF-41-07', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('79', 'KU1.04.12', 'IF-44-12', 'CII3E2', 'Logika Matematika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('80', 'KU2.05.89', 'IF-44-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('81', 'KU1.05.48', 'IF-44-12', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('82', 'KU3.05.54', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('83', 'KU3.05.59', 'IF-44-10', 'CII3E2', 'Logika Matematika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('84', 'KU3.05.40', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('85', 'KU3.05.77', 'IF-44-09', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('86', 'KU3.04.82', 'IF-43-11', 'CII2C9', 'Pengantar Informatika')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('87', 'KU1.05.98', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('88', 'KU2.04.11', 'IF-44-10', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('89', 'KU1.03.22', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('90', 'KU3.05.88', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('91', 'KU2.04.77', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('92', 'KU3.04.84', 'IF-44-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('93', 'KU3.03.98', 'IF-43-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('94', 'KU3.04.33', 'IF-44-09', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('95', 'KU3.05.02', 'IF-43-08', 'CII3N4', 'Sistem Basis Data')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('96', 'KU2.05.80', 'IF-42-12', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('97', 'KU1.01.81', 'IF-42-11', 'CII1H2', 'Kalkulus')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('98', 'KU1.05.80', 'IF-44-12', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('99', 'KU2.04.83', 'IF-43-09', 'CII2B8', 'Dasar Algoritma Pemrograman')
  into data_perkuliahan (kode_perkuliahan, ruangan, kelas, kode_matakuliah, matakuliah) values ('100', 'KU3.05.35', 'IF-44-10', 'CII2B8', 'Dasar Algoritma Pemrograman')
SELECT 1 FROM DUAL;