#Pencarian dengan non-key
#Pencarian data mahasiswa yang berada di jurusan S1 INFORMATIKA
SELECT * FROM MAHASISWA WHERE JURUSAN='S1 INFORMATIKA'

#Pencarian apakah ada nama mahasiwa yang bernama Agnesse Woodyer dan Dosen yang mempunyai NIDN 110862878
SELECT MAHASISWA.NAMA, MAHASISWA.NIM, DOSEN.NAMA, DOSEN.NIDN FROM MAHASISWA,DOSEN WHERE MAHASISWA.NAMA='Agnesse Woodyer' AND DOSEN.NIDN='1108862878'

#Pencarian apakah ada nama mahasiswa yang bernama Emma Braiden, Dosen yang bernama Rob Marchi, dan kode matakuliah CII3N4
SELECT MAHASISWA.NAMA, DOSEN.NAMA, DATA_PERKULIAHAN.KODE_MATAKULIAH FROM MAHASISWA, DOSEN, DATA_PERKULIAHAN WHERE MAHASISWA.NAMA='Emma Braiden' AND DOSEN.NAMA='Rob Marchi' AND DATA_PERKULIAHAN.KODE_MATAKULIAH='CII3N4'

#Pencarian dengan key
#Mencari data mahasiswa yang melakukan perkuliahan dengan kode perkuliahan 01
SELECT MAHASISWA.NAMA, MAHASISWA.NIM, DATA_PERKULIAHAN.KODE_MATAKULIAH, DATA_PERKULIAHAN.MATAKULIAH FROM MAHASISWA JOIN DATA_PERKULIAHAN ON MAHASISWA.KODE_PERKULIAHAN=DATA_PERKULIAHAN.KODE_PERKULIAHAN WHERE DATA_PERKULIAHAN.KODE_PERKULIAHAN='01'

#Mencari data mahasiswa dan dosen yang melakukan perkuliahan dengan kode perkuliahan 50
SELECT MAHASISWA.NAMA, MAHASISWA.NIM, DOSEN.NAMA, DOSEN.NIDN, DATA_PERKULIAHAN.KODE_MATAKULIAH, DATA_PERKULIAHAN.MATAKULIAH FROM MAHASISWA JOIN DATA_PERKULIAHAN ON MAHASISWA.KODE_PERKULIAHAN=DATA_PERKULIAHAN.KODE_PERKULIAHAN JOIN DOSEN ON DATA_PERKULIAHAN.KODE_PERKULIAHAN=DOSEN.KODE_PERKULIAHAN WHERE DATA_PERKULIAHAN.KODE_PERKULIAHAN='50'

